name: API CI/CD - Banking System

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Instalar Redocly
        run: npm install -g @redocly/cli

      - name: Validar y Generar HTML
        run: |
          redocly lint openapi.yaml
          redocly build-docs openapi.yaml -o index.html

      - name: Subir a GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Desplegar Documentación
        uses: actions/deploy-pages@v4
